app:
  title: ${ORG_NAME}
  baseUrl: ${BASE_URL}

organization:
  name: ${ORG_NAME}
backend:
  baseUrl: ${BASE_URL}
#integrations:
#  github:
#    - host: github.com
#      # This is a Personal Access Token or PAT from GitHub. You can find out how to generate this token, and more information
#      # about setting up the GitHub integration here: https://backstage.io/docs/getting-started/configuration#setting-up-a-github-integration
#      apps:
#        - appId: ${APP_ID}
#          clientId: ${CLIENT_ID}
#          clientSecret: ${CLIENT_SECRET}
#          webhookSecret: ${WEBHOOK_SECRET}
#          privateKey: ${PRIVATE_KEY}
#auth:
#  # see https://backstage.io/docs/auth/ to learn about auth providers
#  environment: production
#  providers:
#    github:
#      production:
#        clientId: ${CLIENT_ID}
#        clientSecret: ${CLIENT_SECRET}
#catalog:
#  import:
#    entityFilename: catalog-info.yaml
#    pullRequestBranchName: backstage-integration
#  rules:
#    - allow: [Component, System, API, Resource, Location]
#  providers:
#    github:
#      default:
#        organization: ${GITHUB_ORG} # string
#        schedule: # optional; same options as in TaskScheduleDefinition
#          # supports cron, ISO duration, "human duration" as used in code
#          frequency: { minutes: 30 }
#          # supports ISO duration, "human duration" as used in code
#          timeout: { minutes: 3 }
