apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pelostage
  description: The pelotech backstage application repo
  # Example for optional annotations
  annotations:
    github.com/project-slug: pelotech/pelostage
    backstage.io/techdocs-ref: dir:.
    'backstage.io/kubernetes-id': pelostage
spec:
  type: website
  owner: goup:pelotech/leads
  lifecycle: production
