apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: backstage
    namespace: backstage
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:HIX0TDdTSwyN9mjeVpRp9cExISku3+7ZGs433fbhhSevAVwzTzlinVpEUNyrUB7ykOmPkmumHdr81LvJBKZYyg/97binrSehiGcrlVMSXrMOUwKmAP11rAW3byw/,iv:FVbsT2gyHw7yX1ZFEQnFRLx3/YEolbjIxxstc76ReNE=,tag:8dYJCJ6wL3keVgAkwc6Ytg==,type:str]
    AUTH_GITHUB_CLIENT_ID: ENC[AES256_GCM,data:837Pq0mKu9JCQLi4liUWoEDZGBI=,iv:hlu49oh+ONkKfgN9QacqROUgiuqwE7WEyqgjYLpUnmM=,tag:5Qc1i1Sq1IY1StBqvVLAMg==,type:str]
    AUTH_GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:RqSXhbqnWXJWA8O7cg8PZPkb/KqxP75kowFyCC/GWtn6CPTx+7sgFg==,iv:Vd/wk7ZW/odz6272rUsda1mjf68ZvERnVskeqpRN6fQ=,tag:w46MMwXd0a/ntQ/G819p9w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k2f0a7zedvprs9yr4wgeh5gsvx5rus4k8nyqgt5zgnmrywke5v0qjsr9zd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UkI3RUgzTFhKc0JtaW9w
            Yjd3bUlFMlhISFM4d0ZDQzM2REpJV214b2swCm5UNzdPNjh3QTRjb2NxVVp0V21Q
            djVpSitEYnM1a3pGZ2dIRjdHM281WEEKLS0tIHJjL3ltc05nSU1GY2pFcmVZTWJF
            KzNYWVNJS0kzYzBrVk5MVHRWY2d0ZFUKGn7LKliGk9l6cJKpypJhXNx3R5Y07gmI
            kZcEHG1LFHyBuXMKltMmjaCywv4u7YXtfdYAVHbc1kaGF3CuoSafQw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l3t0mqs7ne26fkpc685axq2f2uvmejlpraq2mqc4z4ucu9cayyzq624737
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwa2V3czg3TDFtanFLOXlp
            UGJoYU1xSWYzQm5zM3BkclJMWUlPcTJzV0VFCjh6dmQ0VlZwM3RqL0p4dSsxM1pG
            MFQxMHNma1VuemV5QWNvd1k4NnkyaUUKLS0tIDF0RXpDdUZVT21DRTFwclhtM3RM
            OXVWN083bDV2YURJaE9obXZnY0VHWTgKBwrvSXPc4ZxAld4cWz+hdzhW87QYCpom
            JE7E5WG3BkcsmwhwXS22Z6ZYwxSnkxbqTml+kt8Bmtp5YM4Mt2ajtg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1v2v40v65vf538nvzfge3gkcw9w30sxmep5ar047clu6msa5fduwq46j9ja
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1VXFNNThaK0ZaZXpwUG9s
            eFpiUU1oL24zaHRkRXFPRjBlbExxSVQrVlNnClNoRlJwR2ZubmdlUDMrRXFUeUJj
            RG9rblNrTzgrak9zdlRLRUY3elZtZmsKLS0tIE8vUTFsSWNyakRBL1lsV3VlcFZw
            cGp3YkhJNDh0ZnRPL0RGUnV4NFljL28K18lDu1/jp3OSY8tE1qPT5z+m/pYPLxXY
            Yy2nCdC7g2g6cMHPnduls5vONj/iUp0e8CpT4NpWuUkipBUaSGEqAQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xk3wzjapukc6cjwdrwg5302pl2a7qy3epe97sccjplxkgc3l7qssgy3g6n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhbUNVTzU4N20vM2hFY0Vy
            azZhOFk0NWVwc21hd2NEdEpIaStjUHJ6NENVCmdOTVFzSkUxMGFxRlRsd1NRbk5W
            dEU3WTdrZGhuMEdFc2RXTUVaOWMyd2cKLS0tIGpRM1cyRUNGTUhSeHA0L0VodzlI
            d1lEYmVmaUxIZlFzR0RJbnUzV04yTUkKHiZM+OjAndqFrSJ4mK0WH9MAu9YNr6eJ
            EV9+dZrTOMyTq/+iGZsylWbVwqlO96ZFfHk8RPUalJxst4/v89vxZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-03T21:58:13Z"
    mac: ENC[AES256_GCM,data:5DRHxR8/uogkLDke9wt0Rbe7g0xM1sIaUKDoyaJZC1kqbRU7jY27nLDBmXCDs2/UOCBhwq/a4P2exSP5oA712fuganv5UgE1i8ZWR1Ew4BfP0OtYakqL1/cM6fgSkCHKfSC32JVfFPoKmxnOXeJdoCa6g3GJCUcAIV1UFZNYJHc=,iv:EkO4P5G7g6hwpsqlFILfEozKX4i6zg2iUA0UbzDrY0g=,tag:Wo2uIRPpOhjp8r8iGpOE0A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
