apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: backstage
    namespace: backstage
stringData:
    APP_ID: ENC[AES256_GCM,data:vTlIJROD,iv:1mEbrucTvit5afTMozd/pYMx3haZDC2qglEHduuEKfA=,tag:2WaZiG4845oeZ7SaiWH0sg==,type:str]
    WEBHOOK_URL: ENC[AES256_GCM,data:OBgk1aYImvrVmAIuDSm2ntnWgeRiZWOzGPeLnQzG3ecSovY=,iv:Ad1hmGL8v1wszTdUiNXG/BoioG3lQvpYjf9BTRXxh3w=,tag:kG5z4WS2l5gh1SK4S3HXUQ==,type:str]
    CLIENT_ID: ENC[AES256_GCM,data:oUbbII8cnEFdURS8ksPgWv4vSAE=,iv:QbvMc9eQ2lo7vIJ/MzdK06T9uBZamrK5KdhYeBRLc84=,tag:su/Ld+H+o2mYzcnTT2HjjA==,type:str]
    CLIENT_SECRET: ENC[AES256_GCM,data:I1WjhVyPun+Moeyq1ciq6Ti5DlMW4W+DuOWYIp57hPldYl4Jxo4SRA==,iv:dxUujVn96OTi7DyRf0dhpspBZyrsCVfGT2MfHFdr+BU=,tag:h72z1wKyUvT2AutPOqgTZQ==,type:str]
    WEBHOOK_SECRET: ENC[AES256_GCM,data:+jvY18N+zfbvKcQtst5guY+hgeanQEEGj72oh1jFUAqC7mLANYXBqQ==,iv:Cm9Q6EHVEg1C9wiNT7ODl9oRqwsWi1GDu2LtktWJw+8=,tag:XtAIWSw8WwYlCBJ8SNX4Kw==,type:str]
    PRIVATE_KEY: ENC[AES256_GCM,data:NW2rM2ygzCB2CNrEYF7TaOXcRXJYYJ4RxHWTzoeFcb5nV++6NZy/Ax1TI+aVp6S8K8ieS+anGguYfsc55dUmthyuvfWa5gLA/eOyP2z3W2yURin+BoUpf0OFOUyXelGlTTU+qcME1L4KwbCIxU39PB1Hyq621S1Sy0ELRsNZ1FK1yP/7Oso4E7vLMOOE3kE5ddMb0KwCICQHMjqJRvajraFvZRYw5Umpz4IJnE9MLIwFcvLlKNCH2W1n0jIS6+iDqCNdKYN5OLBZYNidu01PVWn047bPG5MZI1XYDpOGRUlUcShwJGyqUud+/9eVK1CtCz3hsEtCHWzHS5U0ZadZdSH/uhRTj5blLSqvwftEi2hN4bwNcj5fCRVsE5M0ShP1QMXgDwq71e9W2gybw1P0lYpPnrQtAIgMOUzjW3lIRnBjX0upyFNoOi5Gbntm7lPZ/3aKO3rNP9Qt511DqO958FZ9W3jaU81jI1PZ9Gcm9CJeIHZYm7oB2MfsnQoSzoxxWvwWipdawwOEmnoP//YHRM7D9DouwzFV3rxkyYN+5JucPralh7ElixsbP0aPxNir9ZkwJAL0fAqn7Ru+fESkJH2fwhCLWdD0hG9yMT3GCF6VXN5QpX4s3/PUiJBqg2RRaTod1mSxmag1B+1ph63Rs4y0qKaWqLIG+kAR5F9UKkLi2sWdeaYft5GTYbOHO+ImlRiwhNBb+SXr6+Y7nLaXePZWIj6NhiiigdpkWbD2xVrUoaXR1HOaXUvDXtapKik6Mw1hD1cEccUSpdR0Yc6cSWUDuzBdbthL6TwIWoR9X8j6xGjMB84UZ8dZIZt3/7fzA2+V0DgSxuvlalKVjC3WYKQupppI/NbS+F+uWfDuKpdRuKfL9840mtIeyhgZxPZCNr8BzI0COSHiFMItD8AegMQcP7Y/OEmRbFoRLjc8l/OjFKvUH4IDqDv+g/XyAQOTODnmxNG9y63E6vxkFU1KQne6QcDUlUhb+bWveErGMkRB57j+Z4II3g2JJyPcoWnBpxEFxyRU+euXtCr7SG+voF/2ZzxjFwzwPQycPchzTZ4p6G5fiqzPmCGSKo64Zce0IBF1gnvWTr2Ev3OYREKMzNQ2XwhBWD4qFfS6pOdEMf85oP8ILK1ZbPVIrV/yzJPBQEwZC0VO62l4tCVUqkveASmsK2MqUBlznElRt8bgZQ5vzRMBJ8u2d0qXxApj5LFx00P33QFFQq8YDyQ7ajtRWJiFjCsnOsyNgAsRdJM9PnAsSBT9FpiM5ykfomDlPoUJtPOoDM68IyV6G8gkdpLMHE5Z4DKjldm5qLCtPShAsfkhXo97lp2y5DgZWb4T50Uor9b3YuUcy9LCadpdUsbmMDhioWGWyEQVNxT/gnxsftDdXThtHyaELT7ZmX+EFdrCUfbEClWZdQ0GpEZa0hZSOEGNp1JTg65wAn7UmZyh1dS7b+19ynNYcPBI8NnuTKrPwhqrZqz0BBFoX5W3ofQTqCxRKWyvCokLZX3A8z/hvBN0FqL4rwCE2ZtgfHPOSqBhQuRnp6zuEKCVZAkYy65v0pJLvzSzTPJCp+d7dNLo55KfwHpNZgbZjAFzTsgLc9jPl7vN/g1hPuqhP9esRwT9I7UaYF8iQjv+3de4aWXw3FXzN4DZQjQpDaYsUNOaOHfldnVqlTF1M07Ar7o+JwWKBrRl0LJ8WV71fuWBzrWsoKRpZw8lrNM/u30ycouyUFBU5XwP9GJudd3CROXgTpWkgyI3mdUzZhhz1O90hE2PErc7q7FbBYGj5/zKMS800dOoWoEc8TMTDP887X5aJk/Iqq+eNMVuO/qjyBXObVW+wk9XtIIrVwsidqluM9mGaJLJdlSMVQojEYnGEYLJIvMqoqaz1xi0ZXl6ljo/GMoZdvGaJM7apJLTrTELQUFDAiQa1iPDiOzNHMdnizL6iEjAV2q82b2FxcUDklKBuby65nQvv5X4baWFpqfMdTBO2hV5ZiRqXUxKdsS2NaUAD/w+8/jw/0Lkk/ig19cCLQbKz+6beD/i/XPQFWneMtm2QmNxXwP79ug0Y0CEmw7qsjFGSLMS7GlsYsHSMb145RgZbhSzM4aFCWKLwI9f4UPd3FexLRMV8m+PZAuXSl6jJfLYPIP+Lw3IWCS9A4GEJUr86RTzyHwk6At1ZLeRqlFakYCMOPDxGzu6gXXd+mIbbSUmsPB8T1TSrvUiHTOWauZfOe2JmnQNZRjMAsslvw==,iv:7wdXDT277Af8Rh+VKoQSst5T3Ovbw6SObWfR/M5euzU=,tag:O/Vw/VMC6nJ6L0DvkYy58A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-18T17:19:03Z"
    mac: ENC[AES256_GCM,data:qL3cmEV5iFn5YTUCdp3jKHml2nqwFYcwd2JbZN28/v3umqpVTuWYUBCuTPbObgTyMlACzZJz5hTVpVT4RJGIbnL91jFJ2qnDPuoa2G2+seaQawUNlNfnAYc7JgKBagXIOwdoz/KswLMrJZauDYMBnW6exrgnN8/pAxX/GZba0mI=,iv:3KKSDBee6s80187Q+EjE+nDsrBnYytjk5UR8aJ/IweI=,tag:9YZQbf/irGoSVqGEUhLrKw==,type:str]
    pgp:
        - created_at: "2024-01-18T17:19:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA1ec3WnJ73lUAQ/7BVajFHWIHlchvIGarqAgbJK9wDQBIM2/uD1Bv4xWSb9r
            POr067evSrpO4m8uAscg936Qt0f4JFLXOwXthIwGbHzatp66L+x5EC9Y6O+9lrcJ
            2Bl4Mcn/N0z1mKul2XhH+r748hq6jCs35B4noRZJimoUVsR7GxavE2mV4pKuGQlx
            BaAZyRY2+s9iJvZCR1pT3ZTTFPSnMrt+4fT7O0ja0PGIG0HQ7fO6HrhH4eS+XciC
            wUaOCWSDDNhyJMQ6ZNW4hXCEjRQ7lft0AMhTUR+fg10PupJQBnbVdw9JKm/J2HEX
            bV5ovDSui89L8xhgJvCmSeTACjLoI2vF6cYGU984JwswVzOPC2rlEazAI7r0m6P6
            7FLTSHEX5YX/FoeRHQ4vxfLtS7mTuhYw9sYPiIHUdNa+LqtFgK/iE+UKlp8fXDFZ
            CJlVMd8sajKNf7YW2usi7iNouLU7mJd6V6hVHXuiCE4UBS23nbiWXoi/D3FE7avy
            Sv6NZ2s6vhDSIvHh9J5r8RwKv4SHMacmJ+csiVzYntTfjuh/iTOUw2Y9r92CC9xV
            wuetd7/oIWA75kZFpgL98Q2sSNN4JJhZ4JVBsWVACGS2DXOnNAAqERSFNnRYtWGh
            5m1skn8d3ruQ1zPBUwZN5Dh67KFB867dBzlC5cttdqzJveuu596Q0RYQxuReC9LS
            UQHTjyseo5c2Dhu39QyVqgGx3wFaPUst+8sUppIVn4rAcjE/uDQ2NUlJ+YDmp0tq
            gA9NL1BrHF/0N0kI9mtvfhObj6haQEhiSxvjNCidXCkRLg==
            =5QgG
            -----END PGP MESSAGE-----
          fp: A86483E5975AB10CB83CB9524391E44ED5D6BB46
        - created_at: "2024-01-18T17:19:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA+R/F2ZcM+LfARAAqpuSWnelpmTjowJI4uOwxHycx/drEIMRtRMo3BnOfRu9
            oZaNOlm76SfR1n0t329Lk3/Zl3nMaQpQ8xEoQKl05ZPRQqCBGSrwAJ1e+chjERu2
            HfMYXsWLSwAA6dKpg5Z6opSDQcERtCNaxE2YTSe4XJy20ua2QXCJsbH8xCYXUKxn
            R2sFKZ+HDpCbdaziP7wvXn6CG3pi9+3Bjule1HBc+Kfy2oYwm0KC19/PWhhyjuyK
            uBZDRYy2ajgS/x9gsdtVVClOfYABCCrXF1NO6I2PtCSbc5Mbgc2dxWTr4nVgSSKV
            4HF6gfY13SYctI1aK9Bcpk63wPxYc9z4k7z9yL+8zQMs5WpxXpeScy4Gc/glJKPx
            8uXJiNP/alcARDqv5yItJwV9UuhHCN6qqUodQkXY/3l6VNZdiXQFYcz4EjYPDqAl
            i5isPANxhG7C5aw1C3/1lysm0jhaTt+BbqDFJiPV0YQbTXjXVXJoRFNohRfYkaYi
            1+Xm5ELcdi2+nj1kSCLXytDWjFB5PmK3xNKqdL2fT2lrgMssYgbetwRwSf1Qwb5c
            mVqgJcizg98q+52E5iHLngbfGwKTyfkDcF1rpn+rZROiWdTfjQL7UoNs5RnoH+Wx
            kx2vQ/VFDfOh5vyuYqV4yv7+yHAw+kYOZhxrWHMlgc2AGwrDPstB1yL6wd1qUqjS
            UQFSC276w+qguCLBmdsjY8HuwAkJbHfoVT8KtlDSCfJryWPdfFClc4GCT0ZV82qy
            OM2NjbJxFgk/zpCFUMTkxddwGgyQ3sk2Mz3A3ru5RpvBcQ==
            =XSQ9
            -----END PGP MESSAGE-----
          fp: 4D798019DF930FEA528B876F9A9A6A4CE08B3513
        - created_at: "2024-01-18T17:19:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMA02K0UFJg3roAQgAkwT5yJ8xXeL7EijSEs6WaoGqEBrGB4+8vVmBRfVgVxit
            1wet793fyV10Fo7Y3DkzYchBbLaS3+HOW8RzLxtylnUmfom4xfiUVOabFTDwj1X/
            CvMsFLa9hRHfgDeOYh3nO3jrTFnmyb56yV4JCskCc/aC/IlaQMHZDG00EI1atL/Z
            NY3qD0n3Z77wk5ZGXcUriSVnqA9FNL5k1HJW5yR1L3LXkchkCIctrtrvNIHzBAL0
            keUuYlJp1c/Ou61RJVvnQVKPQtkl2TJIJGQqV+PhVe7wLuIO0e60W3pRm51EEGaO
            7jY62K+mA8S08m9UxIhK6n45q4nUn7qg0k8LPoRfQdJRAW+veVYdtkxB3aAxkpcx
            n9O8fJVgG7pksUTAwN6EvJZdc11ZcGAYH2rWtPH77owgJ+3nYzLjc4ARRhIsFn9O
            xbpYcSetehEdseHuv43esN4O
            =D50i
            -----END PGP MESSAGE-----
          fp: 2331198120BA4D7B91AEFCFA8D9E179B9651F677
        - created_at: "2024-01-18T17:19:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4Q0rVELwN4AAQ//Q70dNgkuIf2nGvSTTl9ni429/ag3MvbDIYnGmZa6oacy
            7QqzXcW3N6uLopoSHBTLrz1UbI6ZYeH5KsviIBTV9Wr0Q4ZUBz8sTOlRys0TXc0o
            oxorC4LbSc/hO8SCPLPfcGQu8n9p0A/iT02FuvfMGNYDg0/YufZ9fpZ4awINmO5n
            EvqH8nwxvBN1iKHTpt5tn304scrygWGIhRoVgeKRMWhpFQIGNDtM7x+t2lyT0b7W
            xF6O0hPGYYP/VwGfqT7F8207NtAKnHgFwm0ytqWlTf+js7EjWKRa07UINgmEqqPG
            gzPS6N62XlPCcf0JNTbv04xe99gBlUTYugAHCPdGVpUhWHgKSgev1xJ71uZ4ZeCv
            9miwewN39a/NHOGIBkm1X1LEs0t/ARFz8kxnR+hNUjZNQUwcES5DykNq8pEeQyt9
            t8uQhpBg9zgb0JCv6g4HIRke0H8TC+7KiDqH7LiPjYnkHIu5qi4nlWdqg61zdJUk
            EGjj7wpiEmSTtRawFUkRikOjAYPvA9Rs6xNBDBWeFrmXKzSecrM7IhRp7bHanBX8
            EdAhbefAZL9/yyZUd8SJCrY4MIO+gbGE0nVydsKouZ2KmWXWbwQ+htTZJCXkRfoh
            Qy93fj2N/uHmLQ5VuvU19cdlSLLxgn//FgtaJgHAjwNue3aAWZnu9dsHDcRNsTvU
            ZgEJAhAsKD4QZbWHnbax7nlnvpppy3sypqAg5PbeFax5fwn1ho7o+A0s7kTHYv8T
            Bp5bp/fN3Xc2KPzTe2kJG7etDgODc2ctHi4wTEO+a9Es+jIJONYrXcPrM1IeZtb4
            PyyDGZo1OA==
            =KT3o
            -----END PGP MESSAGE-----
          fp: 857940658682B76F60D96892CA87572D47FF66B7
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
