apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pelostage.yaml
  - namespace.yaml

images:
  - name: ghcr.io/pelotech/pelostage
    newTag: latest

namespace: backstage
