---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: pelostage-ingress
  namespace: backstage
spec:
  ingressClassName: nginx
  rules:
    - host: backstage.host
      http:
        paths:
          - backend:
              service:
                name: backstage
                port:
                  name: http
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - backstage.host
      secretName: pelostage-secret

---
apiVersion: v1
kind: Service
metadata:
  name: backstage
  namespace: backstage
spec:
  selector:
    app: backstage
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      serviceAccountName: backstage
      containers:
        - name: backstage
          image: ghcr.io/pelotech/pelostage:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 7007
          env:
            - name: K8S_TOKEN
              valueFrom:
                secretKeyRef:
                  name: backstage-sa
                  key: token
          envFrom:
            - secretRef:
                name: backstage
            - configMapRef:
                name: backstage
# Uncomment if health checks are enabled in your app:
# https://backstage.io/docs/plugins/observability#health-checks
#          readinessProbe:
#            httpGet:
#              port: 7007
#              path: /healthcheck
#          livenessProbe:
#            httpGet:
#              port: 7007
#              path: /healthcheck
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backstage-read-only
rules:
  - apiGroups:
      - '*'
    resources:
      - pods
      - configmaps
      - services
      - deployments
      - replicasets
      - horizontalpodautoscalers
      - ingresses
      - statefulsets
      - limitranges
      - daemonsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
      - cronjobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - metrics.k8s.io
    resources:
      - pods
    verbs:
      - get
      - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backstage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backstage
subjects:
  - kind: ServiceAccount
    name: backstage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: backstage-read-only
---
apiVersion: v1
kind: Secret
metadata:
  name: backstage-sa
  annotations:
    kubernetes.io/service-account.name: backstage
type: kubernetes.io/service-account-token