apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  owner: pelotech

commonLabels:
  backstage.io/kubernetes-id: pelostage

resources:
  - ../../base
  - config-map.yaml

patches:
  - target:
      kind: Ingress
      name: pelostage-ingress
    path: ingress-patch.yaml


generators:
  - generators/secrets-generator.yaml

namespace: backstage
