apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  owner: pelotech

resources:
  - ../../base

patches:
  - target:
      kind: Ingress
      name: pelostage-ingress
    path: ingress-patch.yaml
  - target:
      kind: Deployment
      name: backstage
    path: deployment-patch.yaml


generators:
  - generators/secrets-generator.yaml

namespace: backstage
