apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/instance: "argocd"
commonAnnotations:
  owner: pelotech

resources:
  - base/pelostage.yaml
  - base/namespace.yaml

generators:
  - generators/secrets-generator.yaml

namespace: backstage
