name: Publish Docker image

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
    paths-ignore:
      - 'README.md'
      - 'gitops/**'
      - 'docs/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run make ci-build in dev container
        uses: devcontainers/ci@v0.3
        with:
          # [Optional] If you have a separate workflow like the one above
          # to pre-build your container image, you can reference it here
          # to speed up your application build workflows as well!
          cacheFrom: ghcr.io/example/example-devcontainer
          push: never
          runCmd: |
            yarn install --frozen-lockfile
            yarn tsc
            yarn build:all

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
            # tag event
            type=ref,event=tag
      - name: sha short
        if: github.ref_type == 'branch'
        id: sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Build and push Docker image sha
        if: github.ref_type == 'branch'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: packages/backend/Dockerfile
          push: true
          build-args: |
            BUILD_VERSION=${{ steps.sha.outputs.sha_short }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Build and push Docker image tag
        uses: docker/build-push-action@v3
        if: github.ref_type == 'tag'
        with:
          context: .
          file: packages/backend/Dockerfile
          push: true
          build-args: |
            BUILD_VERSION=${{ github.ref_name }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
